<h1>Содержание<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Загрузка-данных" data-toc-modified-id="Загрузка-данных-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Загрузка данных</a></span></li><li><span><a href="#Умножение-матриц" data-toc-modified-id="Умножение-матриц-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Умножение матриц</a></span></li><li><span><a href="#Алгоритм-преобразования" data-toc-modified-id="Алгоритм-преобразования-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Алгоритм преобразования</a></span></li><li><span><a href="#Проверка-алгоритма" data-toc-modified-id="Проверка-алгоритма-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>Проверка алгоритма</a></span></li><li><span><a href="#Чек-лист-проверки" data-toc-modified-id="Чек-лист-проверки-5"><span class="toc-item-num">5&nbsp;&nbsp;</span>Чек-лист проверки</a></span></li></ul></div>

# Защита персональных данных клиентов

Вам нужно защитить данные клиентов страховой компании «Хоть потоп». Разработайте такой метод преобразования данных, чтобы по ним было сложно восстановить персональную информацию. Обоснуйте корректность его работы.

Нужно защитить данные, чтобы при преобразовании качество моделей машинного обучения не ухудшилось. Подбирать наилучшую модель не требуется.

**Описание данных**

Набор данных находится в файле /datasets/insurance.csv.
- **Признаки:** пол, возраст и зарплата застрахованного, количество членов его семьи.
- Целевой признак: количество страховых выплат клиенту за последние 5 лет.

## Загрузка данных

In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score

In [2]:
df = pd.read_csv('/datasets/insurance.csv')
print(df.head(10))
print(df.shape)
print(df.info())

   Пол  Возраст  Зарплата  Члены семьи  Страховые выплаты
0    1     41.0   49600.0            1                  0
1    0     46.0   38000.0            1                  1
2    0     29.0   21000.0            0                  0
3    0     21.0   41700.0            2                  0
4    1     28.0   26100.0            0                  0
5    1     43.0   41000.0            2                  1
6    1     39.0   39700.0            2                  0
7    1     25.0   38600.0            4                  0
8    1     36.0   49700.0            1                  0
9    1     32.0   51700.0            1                  0
(5000, 5)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 5 columns):
Пол                  5000 non-null int64
Возраст              5000 non-null float64
Зарплата             5000 non-null float64
Члены семьи          5000 non-null int64
Страховые выплаты    5000 non-null int64
dtypes: float64(2), int64(3)
memory u

## Умножение матриц

Ответьте на вопрос и обоснуйте решение.
Признаки умножают на обратимую матрицу. Изменится ли качество линейной регрессии? (Её можно обучить заново.)

В этом задании вы можете записывать формулы в *Jupyter Notebook.*

Чтобы записать формулу внутри текста, окружите её символами доллара \\$; если снаружи —  двойными символами \\$\\$. Эти формулы записываются на языке вёрстки *LaTeX.* 

Для примера мы записали формулы линейной регрессии. Можете их скопировать и отредактировать, чтобы решить задачу.

Работать в *LaTeX* необязательно.

Обозначения:

- $X$ — матрица признаков (нулевой столбец состоит из единиц)

- $y$ — вектор целевого признака

- $P$ — матрица, на которую умножаются признаки

- $w$ — вектор весов линейной регрессии (нулевой элемент равен сдвигу)

Предсказания:

$$
a = Xw
$$

Задача обучения:

$$
w = \arg\min_w MSE(Xw, y)
$$

Формула обучения:

$$
w = (X^T X)^{-1} X^T y
$$

**Ответ:**

При умножении признаков на обратимую матрицу качество линейной регрессии не изменится.

**Обоснование:**

Обозначим:
- $X' = X P$ - преобразованная матрица признаков, полученная путем умножения исходной матрицы на обратимую матрицу
- $w'$ - вектор весов линейной регрессии, полученный обучением на преобразованной матрице признаков
- $a'$ - вектор предсказаний модели, обученной на преобразованной матрице признаков

$$
w' = ((X P)^T X P)^{-1} (X P)^T y
$$
Используя свойства матриц:
- $ A (B C) = (A B) C$ - Свойство ассоциативности матриц
- $ (A B)^{-1} = B^{-1} A^{-1} $- Обратная матрица от произведения двух матриц равна произведению обратных матриц
- $ (A B)^T = B^T A^T $ - Транспонированное произведение матриц равно произведению транспонированных матриц

преобразуем формулу:

$$
w' = (P^T X^T X P)^{-1} P^T X^T y
$$
$$
w' = P^{-1} (X^T X)^{-1} (P^T)^{-1} P^T X^T y
$$
Т.к. $ (P^T)^{-1} P^T = E $ (умножение матрицы на свою обратную равно единичной матрице $ E $), то
$$
w' = P^{-1} (X^T X)^{-1} E X^T y
$$
где $ E X^T = X^T $, получим:
$$
w' = P^{-1} (X^T X)^{-1} X^T y
$$
$$
w' = P^{-1} w
$$

Следовательно, вектор предсказаний
$$
a' = X' P^{-1} w
$$
где $ X' = X P $
$$
a' = X P P^{-1} w
$$
$$
a' = X E w
$$
$$
a' = X w
$$
Т.е. $ a = a' $

Что и требовалось доказать.

## Алгоритм преобразования

**Алгоритм**

In [3]:
#Функция шифрования матрицы
def cifer(x):
    X = x.to_numpy()
    while True:
        try:
            K = np.random.rand(x.shape[1],x.shape[1])
            inv = np.linalg.inv(K)
            break
        except LinAlgError:
            continue
    X_cifered = np.dot(X, K)
    return X_cifered, K

In [4]:
x = df.drop('Страховые выплаты', axis=1)
y = df['Страховые выплаты']

In [5]:
X_new, K = cifer(x)

In [6]:
print('Зашифрованные признаки:')
print(X_new)
print('Матрица-ключ:')
print(K)

Зашифрованные признаки:
[[3.17177862e+01 4.19006286e+04 4.45311617e+04 5.70507489e+03]
 [3.52723148e+01 3.21121246e+04 3.41294235e+04 4.38452434e+03]
 [2.21463437e+01 1.77483689e+04 1.88638682e+04 2.42636639e+03]
 ...
 [1.56685280e+01 2.86324538e+04 3.04291839e+04 3.89131884e+03]
 [1.73607582e+01 2.76226231e+04 2.93549404e+04 3.75710868e+03]
 [2.17945638e+01 3.42937502e+04 3.64461481e+04 4.66464942e+03]]
Матрица-ключ:
[[1.00159212e-01 6.27298483e-01 4.24861080e-02 6.55710271e-01]
 [7.55881360e-01 7.60465608e-01 8.72811530e-01 9.69774686e-01]
 [1.07516327e-05 8.44110258e-01 8.97074125e-01 1.14202044e-01]
 [9.32102402e-02 9.53385344e-01 4.57402690e-01 2.37028626e-01]]


In [7]:
#Получим обратный ключ и проведем дешифрование
K_inv = np.linalg.inv(K)
X_decifered = np.dot(X_new, K_inv)

print(X_decifered)

[[ 1.00000000e+00  4.10000000e+01  4.96000000e+04  1.00000000e+00]
 [-1.07017884e-12  4.60000000e+01  3.80000000e+04  1.00000000e+00]
 [ 3.86420928e-13  2.90000000e+01  2.10000000e+04 -6.53148146e-12]
 ...
 [-1.13327087e-12  2.00000000e+01  3.39000000e+04  2.00000000e+00]
 [ 1.00000000e+00  2.20000000e+01  3.27000000e+04  3.00000000e+00]
 [ 1.00000000e+00  2.80000000e+01  4.06000000e+04  1.00000000e+00]]


**Обоснование**

Чтобы получить зашифрованный массив признаков, мы умножили исходную матрицу на квадратную обратимую матрицу P, размер которой равен количеству признаков. Зашифрованная матрица имеет ту же размерность что и исходная. Согласно доказательству выше, предсказания модели, обученной и примененной на матрицах, полученным умножением исходных на обратимую (матрица-ключ), будет идентичным.

## Проверка алгоритма

Обучим и проверим модель на данных без шифрования

In [8]:
X_train, X_valid, y_train, y_valid = train_test_split(x, y, test_size=0.25, random_state=123)
model = LinearRegression()
model.fit(X_train, y_train)
predicted = model.predict(X_valid)
print("R2 =", r2_score(y_valid, predicted))

R2 = 0.43018469990933306


Сравним с моделью на зашифрованных данных

In [9]:
x_cifered, _ = cifer(x)
X_train_c, X_valid_c, y_train, y_valid = train_test_split(x_cifered, y, test_size=0.25, random_state=123)
model = LinearRegression()
model.fit(X_train_c, y_train)
predicted  = model.predict(X_valid_c)
print("R2 =", r2_score(y_valid, predicted))

R2 = 0.43018469990943775


**Вывод**

Как видим, R2 двух моделей получились одинаковыми.

Поставьте 'x' в выполненных пунктах. Далее нажмите Shift+Enter.